"""initial_schema

Revision ID: fc127823c853
Revises: 
Create Date: 2026-07-06 09:51:16.284885

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = 'fc127823c853'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('material_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_categories_name'), 'material_categories', ['name'], unique=True)
    op.create_table('subcontractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractors_name'), 'subcontractors', ['name'], unique=False)
    op.create_index(op.f('ix_subcontractors_status'), 'subcontractors', ['status'], unique=False)
    op.create_index(op.f('ix_subcontractors_trade'), 'subcontractors', ['trade'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_category'), 'suppliers', ['category'], unique=False)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_name'), 'suppliers', ['supplier_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('ai_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workflow', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_excerpt', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_logs_user_id'), 'ai_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_audit_logs_workflow'), 'ai_audit_logs', ['workflow'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_city'), 'projects', ['city'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_project_id'), 'ai_conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['ai_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memories_category'), 'ai_memories', ['category'], unique=False)
    op.create_index(op.f('ix_ai_memories_project_id'), 'ai_memories', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_memories_source_type'), 'ai_memories', ['source_type'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('workflow', sa.String(length=100), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('structured_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_project_id'), 'ai_recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_status'), 'ai_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_workflow'), 'ai_recommendations', ['workflow'], unique=False)
    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('summary_type', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_project_id'), 'ai_summaries', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_summary_type'), 'ai_summaries', ['summary_type'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_action_type'), 'approval_requests', ['action_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_project_id'), 'approval_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_risk_level'), 'approval_requests', ['risk_level'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('change_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('co_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_orders_co_number'), 'change_orders', ['co_number'], unique=False)
    op.create_index(op.f('ix_change_orders_project_id'), 'change_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_change_orders_status'), 'change_orders', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=False)
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_project_id'), 'claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('correspondence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('related_record_type', sa.String(length=50), nullable=False),
    sa.Column('related_record_id', sa.Integer(), nullable=False),
    sa.Column('sent_date', sa.Date(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correspondence_project_id'), 'correspondence', ['project_id'], unique=False)
    op.create_index(op.f('ix_correspondence_related_record_id'), 'correspondence', ['related_record_id'], unique=False)
    op.create_index(op.f('ix_correspondence_related_record_type'), 'correspondence', ['related_record_type'], unique=False)
    op.create_index(op.f('ix_correspondence_sent_date'), 'correspondence', ['sent_date'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_project_id'), 'document_embeddings', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_source_id'), 'document_embeddings', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_source_type'), 'document_embeddings', ['source_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('related_record_id', sa.Integer(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_documents_project_id'), 'generated_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_related_record_id'), 'generated_documents', ['related_record_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_type'), 'generated_documents', ['type'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_meeting_date'), 'meetings', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_type'), 'meetings', ['meeting_type'], unique=False)
    op.create_index(op.f('ix_meetings_project_id'), 'meetings', ['project_id'], unique=False)
    op.create_table('ncrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
    sa.Column('ncr_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ncrs_issue_date'), 'ncrs', ['issue_date'], unique=False)
    op.create_index(op.f('ix_ncrs_ncr_type'), 'ncrs', ['ncr_type'], unique=False)
    op.create_index(op.f('ix_ncrs_project_id'), 'ncrs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ncrs_status'), 'ncrs', ['status'], unique=False)
    op.create_index(op.f('ix_ncrs_subcontractor_id'), 'ncrs', ['subcontractor_id'], unique=False)
    op.create_index(op.f('ix_ncrs_supplier_id'), 'ncrs', ['supplier_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('planned_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_category', sa.String(length=100), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('planned_manpower', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_activities_activity_category'), 'planned_activities', ['activity_category'], unique=False)
    op.create_index(op.f('ix_planned_activities_project_id'), 'planned_activities', ['project_id'], unique=False)
    op.create_table('project_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_issues_project_id'), 'project_issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_issues_status'), 'project_issues', ['status'], unique=False)
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_milestones_project_id'), 'project_milestones', ['project_id'], unique=False)
    op.create_table('project_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('likelihood', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_risks_project_id'), 'project_risks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_risks_severity'), 'project_risks', ['severity'], unique=False)
    op.create_index(op.f('ix_project_risks_status'), 'project_risks', ['status'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=50), nullable=False),
    sa.Column('material_category', sa.String(length=100), nullable=True),
    sa.Column('material_category_id', sa.Integer(), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('required_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rework_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['material_category_id'], ['material_categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requests_material_category'), 'purchase_requests', ['material_category'], unique=False)
    op.create_index(op.f('ix_purchase_requests_material_category_id'), 'purchase_requests', ['material_category_id'], unique=False)
    op.create_index(op.f('ix_purchase_requests_project_id'), 'purchase_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_requests_request_no'), 'purchase_requests', ['request_no'], unique=False)
    op.create_index(op.f('ix_purchase_requests_status'), 'purchase_requests', ['status'], unique=False)
    op.create_table('rfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rfi_number', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('raised_by', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('raised_date', sa.Date(), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('response_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfis_discipline'), 'rfis', ['discipline'], unique=False)
    op.create_index(op.f('ix_rfis_priority'), 'rfis', ['priority'], unique=False)
    op.create_index(op.f('ix_rfis_project_id'), 'rfis', ['project_id'], unique=False)
    op.create_index(op.f('ix_rfis_raised_date'), 'rfis', ['raised_date'], unique=False)
    op.create_index(op.f('ix_rfis_required_date'), 'rfis', ['required_date'], unique=False)
    op.create_index(op.f('ix_rfis_rfi_number'), 'rfis', ['rfi_number'], unique=False)
    op.create_index(op.f('ix_rfis_status'), 'rfis', ['status'], unique=False)
    op.create_table('safety_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_event_date'), 'safety_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_safety_events_project_id'), 'safety_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_safety_events_severity'), 'safety_events', ['severity'], unique=False)
    op.create_index(op.f('ix_safety_events_subcontractor_id'), 'safety_events', ['subcontractor_id'], unique=False)
    op.create_table('site_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_reports_project_id'), 'site_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_site_reports_report_date'), 'site_reports', ['report_date'], unique=False)
    op.create_table('supplier_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('on_time_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('late_po_count', sa.Integer(), nullable=False),
    sa.Column('ncr_count', sa.Integer(), nullable=False),
    sa.Column('delay_days_total', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_evaluations_project_id'), 'supplier_evaluations', ['project_id'], unique=False)
    op.create_index(op.f('ix_supplier_evaluations_supplier_id'), 'supplier_evaluations', ['supplier_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_request_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_history_approval_request_id'), 'approval_history', ['approval_request_id'], unique=False)
    op.create_table('daily_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=False),
    sa.Column('site_report_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=True),
    sa.Column('activity_description', sa.Text(), nullable=False),
    sa.Column('manpower_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['site_report_id'], ['site_reports.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_activities_activity_date'), 'daily_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_daily_activities_project_id'), 'daily_activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_daily_activities_site_report_id'), 'daily_activities', ['site_report_id'], unique=False)
    op.create_index(op.f('ix_daily_activities_subcontractor_id'), 'daily_activities', ['subcontractor_id'], unique=False)
    op.create_table('meeting_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_action_items_meeting_id'), 'meeting_action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_project_id'), 'meeting_action_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_status'), 'meeting_action_items', ['status'], unique=False)
    op.create_table('project_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_decisions_meeting_id'), 'project_decisions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_project_decisions_project_id'), 'project_decisions', ['project_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('promised_delivery', sa.Date(), nullable=True),
    sa.Column('actual_delivery', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('delay_root_cause', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_is_late'), 'purchase_orders', ['is_late'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_pr_id'), 'purchase_orders', ['pr_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_project_id'), 'purchase_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('change_order_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('correspondence_id', sa.Integer(), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['correspondence_id'], ['correspondence.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['project_decisions.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_evidence_change_order_id'), 'claim_evidence', ['change_order_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_claim_id'), 'claim_evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_correspondence_id'), 'claim_evidence', ['correspondence_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_decision_id'), 'claim_evidence', ['decision_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_document_id'), 'claim_evidence', ['document_id'], unique=False)
    op.create_table('subcontractor_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('schedule_score', sa.Integer(), nullable=False),
    sa.Column('manpower_score', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('linked_safety_event_id', sa.Integer(), nullable=True),
    sa.Column('linked_ncr_id', sa.Integer(), nullable=True),
    sa.Column('linked_daily_activity_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('manpower_score BETWEEN 0 AND 100', name='ck_subeval_manpower'),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 100', name='ck_subeval_quality'),
    sa.CheckConstraint('safety_score BETWEEN 0 AND 100', name='ck_subeval_safety'),
    sa.CheckConstraint('schedule_score BETWEEN 0 AND 100', name='ck_subeval_schedule'),
    sa.ForeignKeyConstraint(['linked_daily_activity_id'], ['daily_activities.id'], ),
    sa.ForeignKeyConstraint(['linked_ncr_id'], ['ncrs.id'], ),
    sa.ForeignKeyConstraint(['linked_safety_event_id'], ['safety_events.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractor_evaluations_project_id'), 'subcontractor_evaluations', ['project_id'], unique=False)
    op.create_index(op.f('ix_subcontractor_evaluations_subcontractor_id'), 'subcontractor_evaluations', ['subcontractor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcontractor_evaluations_subcontractor_id'), table_name='subcontractor_evaluations')
    op.drop_index(op.f('ix_subcontractor_evaluations_project_id'), table_name='subcontractor_evaluations')
    op.drop_table('subcontractor_evaluations')
    op.drop_index(op.f('ix_claim_evidence_document_id'), table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_decision_id'), table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_correspondence_id'), table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_claim_id'), table_name='claim_evidence')
    op.drop_index(op.f('ix_claim_evidence_change_order_id'), table_name='claim_evidence')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_project_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_pr_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_is_late'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_project_decisions_project_id'), table_name='project_decisions')
    op.drop_index(op.f('ix_project_decisions_meeting_id'), table_name='project_decisions')
    op.drop_table('project_decisions')
    op.drop_index(op.f('ix_meeting_action_items_status'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_project_id'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_meeting_id'), table_name='meeting_action_items')
    op.drop_table('meeting_action_items')
    op.drop_index(op.f('ix_daily_activities_subcontractor_id'), table_name='daily_activities')
    op.drop_index(op.f('ix_daily_activities_site_report_id'), table_name='daily_activities')
    op.drop_index(op.f('ix_daily_activities_project_id'), table_name='daily_activities')
    op.drop_index(op.f('ix_daily_activities_activity_date'), table_name='daily_activities')
    op.drop_table('daily_activities')
    op.drop_index(op.f('ix_approval_history_approval_request_id'), table_name='approval_history')
    op.drop_table('approval_history')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_supplier_evaluations_supplier_id'), table_name='supplier_evaluations')
    op.drop_index(op.f('ix_supplier_evaluations_project_id'), table_name='supplier_evaluations')
    op.drop_table('supplier_evaluations')
    op.drop_index(op.f('ix_site_reports_report_date'), table_name='site_reports')
    op.drop_index(op.f('ix_site_reports_project_id'), table_name='site_reports')
    op.drop_table('site_reports')
    op.drop_index(op.f('ix_safety_events_subcontractor_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_severity'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_project_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_event_date'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_rfis_status'), table_name='rfis')
    op.drop_index(op.f('ix_rfis_rfi_number'), table_name='rfis')
    op.drop_index(op.f('ix_rfis_required_date'), table_name='rfis')
    op.drop_index(op.f('ix_rfis_raised_date'), table_name='rfis')
    op.drop_index(op.f('ix_rfis_project_id'), table_name='rfis')
    op.drop_index(op.f('ix_rfis_priority'), table_name='rfis')
    op.drop_index(op.f('ix_rfis_discipline'), table_name='rfis')
    op.drop_table('rfis')
    op.drop_index(op.f('ix_purchase_requests_status'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_request_no'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_project_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_material_category_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_material_category'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index(op.f('ix_project_risks_status'), table_name='project_risks')
    op.drop_index(op.f('ix_project_risks_severity'), table_name='project_risks')
    op.drop_index(op.f('ix_project_risks_project_id'), table_name='project_risks')
    op.drop_table('project_risks')
    op.drop_index(op.f('ix_project_milestones_project_id'), table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index(op.f('ix_project_issues_status'), table_name='project_issues')
    op.drop_index(op.f('ix_project_issues_project_id'), table_name='project_issues')
    op.drop_table('project_issues')
    op.drop_index(op.f('ix_planned_activities_project_id'), table_name='planned_activities')
    op.drop_index(op.f('ix_planned_activities_activity_category'), table_name='planned_activities')
    op.drop_table('planned_activities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ncrs_supplier_id'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_subcontractor_id'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_status'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_project_id'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_ncr_type'), table_name='ncrs')
    op.drop_index(op.f('ix_ncrs_issue_date'), table_name='ncrs')
    op.drop_table('ncrs')
    op.drop_index(op.f('ix_meetings_project_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_type'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_date'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_generated_documents_type'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_related_record_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_project_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_embeddings_source_type'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_source_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_project_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_correspondence_sent_date'), table_name='correspondence')
    op.drop_index(op.f('ix_correspondence_related_record_type'), table_name='correspondence')
    op.drop_index(op.f('ix_correspondence_related_record_id'), table_name='correspondence')
    op.drop_index(op.f('ix_correspondence_project_id'), table_name='correspondence')
    op.drop_table('correspondence')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_project_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_change_orders_status'), table_name='change_orders')
    op.drop_index(op.f('ix_change_orders_project_id'), table_name='change_orders')
    op.drop_index(op.f('ix_change_orders_co_number'), table_name='change_orders')
    op.drop_table('change_orders')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_risk_level'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_project_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_action_type'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_ai_summaries_summary_type'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_project_id'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    op.drop_index(op.f('ix_ai_recommendations_workflow'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_status'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_project_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_ai_memories_source_type'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_project_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_category'), table_name='ai_memories')
    op.drop_table('ai_memories')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_project_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_city'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_ai_audit_logs_workflow'), table_name='ai_audit_logs')
    op.drop_index(op.f('ix_ai_audit_logs_user_id'), table_name='ai_audit_logs')
    op.drop_table('ai_audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_supplier_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_category'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_subcontractors_trade'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_status'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_name'), table_name='subcontractors')
    op.drop_table('subcontractors')
    op.drop_index(op.f('ix_material_categories_name'), table_name='material_categories')
    op.drop_table('material_categories')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
